# ethereum_bookStore


Simple online book store running fully on Ethereum blockchain(https://ethereum.org/). Mainly user can upload pdf books to sell or can buy books from other users.
There are mainly two smart contracts for selling paperback book and pdf books. 

== To play 

=== Install Ipfs 
if you'd like to play with source code , firstly you will need to install ipfs to your machine
https://dist.ipfs.io/#go-ipfs go and download ipfs into your machine  
https://docs.ipfs.io/introduction/usage/ follow this doc for installing ipfs
== run ipfs on terminal
[source, shell]
ipfs daemon


=== Install metamask to your chrome browser:
https://metamask.io/ . After installing metamask, create your ethereum address and set network to ropsten.


=== Install Node.js 
https://nodejs.org/en/

=== Check node.js 
[source, shell]
node -v

=== Install 

Then let's clone this repository. Open a terminal, cd into the directory where you store your projects, and run the following command:
[source, shell]
git clone https://github.com/Aziiiz/ethereum_bookStore.git

Next, cd into ethereum_bookStore
[source, shell]
cd ethereum_bookStore


Install dependencies
[source, shell]
npm install

We're ready to start the web server. In a new terminal, run:
[source, shell]
node app.js


=== Obtaining ethers

If you want to do anything on it , then you'll need to get an account and some ethers. Get some from the Ropsten Testnet Faucet ( https://faucet.metamask.io/ ).



